{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main déplacée à gauche!\n",
      "Main baissée!\n",
      "Main levée!\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "# Plage de couleurs pour le rouge\n",
    "lower_red = np.array([0, 100, 100])\n",
    "upper_red = np.array([10, 255, 255])\n",
    "\n",
    "# Initialisation de la capture vidéo\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "# Variables pour le suivi du mouvement\n",
    "hand_detected = False\n",
    "hand_raised = False\n",
    "hand_lowered = False\n",
    "hand_moved_left = False\n",
    "hand_moved_right = False\n",
    "\n",
    "while True:\n",
    "    # Capture de la vidéo\n",
    "    ret, frame = cap.read()\n",
    "\n",
    "    # Conversion de l'image en espace de couleurs HSV\n",
    "    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)\n",
    "\n",
    "    # Filtrage pour ne conserver que les pixels dans la plage de couleurs rouge\n",
    "    mask = cv2.inRange(hsv, lower_red, upper_red)\n",
    "\n",
    "    # Recherche des contours\n",
    "    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
    "\n",
    "    # Vérification si la main est détectée (contour détecté)\n",
    "    hand_detected = len(contours) > 0\n",
    "\n",
    "    # Vérification de la position de la main\n",
    "    if hand_detected:\n",
    "        # Calcul du centre de la main (coordonnées x, y)\n",
    "        moments = cv2.moments(contours[0])\n",
    "        if moments[\"m00\"] != 0:\n",
    "            cx = int(moments[\"m10\"] / moments[\"m00\"])\n",
    "            cy = int(moments[\"m01\"] / moments[\"m00\"])\n",
    "\n",
    "            # Vérification des mouvements\n",
    "            if not hand_raised and cy < frame.shape[0] // 2:\n",
    "                print(\"Main levée!\")\n",
    "                hand_raised = True\n",
    "                hand_lowered = False\n",
    "            elif not hand_lowered and cy > frame.shape[0] // 1.5:\n",
    "                print(\"Main baissée!\")\n",
    "                hand_raised = False\n",
    "                hand_lowered = True\n",
    "            elif hand_raised and not hand_moved_left and cx < frame.shape[1] // 3:\n",
    "                print(\"Main déplacée à gauche!\")\n",
    "                hand_moved_left = True\n",
    "                hand_moved_right = False\n",
    "            elif hand_raised and not hand_moved_right and cx > 2 * frame.shape[1] // 3:\n",
    "                print(\"Main déplacée à droite!\")\n",
    "                hand_moved_left = False\n",
    "                hand_moved_right = True\n",
    "            else:\n",
    "                hand_moved_left = False\n",
    "                hand_moved_right = False\n",
    "\n",
    "    # Dessin des contours sur l'image originale\n",
    "    cv2.drawContours(frame, contours, -1, (0, 255, 0), 2)\n",
    "\n",
    "    # Affichage de l'image résultante\n",
    "    cv2.imshow('Frame', frame)\n",
    "\n",
    "    # Sortie de la boucle si la touche 'q' est pressée\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "# Libération des ressources\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
